---
- name: CA server preflight
  when: droplet.ca is defined and droplet.ca.server is defined
  import_role:
    name: traviss25.dev.ca
    tasks_from: server_preflight
  vars:
    cert: "{{ droplet.ca.server.cert | default({}) }}"
    key: "{{ droplet.ca.server.key | default({}) }}"

- name: CA client preflight
  when: droplet.ca is defined and droplet.ca.client is defined
  include_role:
    name: traviss25.dev.ca
    tasks_from: client_preflight
  vars:
    ip: "{{ droplet.ip }}"
    cert: "{{ droplet.ca.client.cert | default({}) }}"
    key: "{{ droplet.ca.client.key | default({}) }}"
    subject_alt_names: "{{ droplet.ca.client.subject_alt_names }}"
    ca_server:
      ip: "{{ droplet.ca.client.ca_server.ip }}"

- name: DNS server preflight
  when: droplet.dns is defined and droplet.dns.server is defined
  include_role:
    name: traviss25.dev.dns
    tasks_from: main
  vars:
    server:
      coredns_version: "{{ droplet.dns.coredns_version }}"
      corefile:
        records: "{{ droplet.dns.records }}"

- name: SSH passkey preflight
  include_role:
    name: traviss25.util.ssh
    tasks_from: pass_key_preflight
  vars:
    ip: "{{ droplet.ip }}"
    username: "{{ droplet.user_creds.username }}"
    password: "{{ droplet.user_creds.password }}"

- name: Docker container preflight
  loop: "{{ droplet.docker_containers }}"
  include_role:
    name: traviss25.docker.docker
    tasks_from: container_preflight
  vars:
    container: "{{ item }}"

- name: Docker compose preflight
  loop: "{{ droplet.docker_composes | default([]) }}"
  include_role:
    name: traviss25.docker.docker
    tasks_from: compose_service_preflight
  vars:
    compose: "{{ item }}"
