---
- name: Set docker container facts
  set_fact:
    docker_type_vars: "{{ docker_type.vars }}" &docker_type_vars_ref
    default_docker_type_vars: "{{ default_docker_type[docker_type.name].vars | default({}) }}" &default_docker_type_vars_ref

- name: Import docker role container(s)
  import_role:
    name: traviss25.docker.docker_container
    tasks_from: "{{ docker_type.name }}"
  vars:
    image: "{{ docker_type.image | default(default_docker_type[docker_type.name].image) }}"
    <<: [*default_docker_type_vars_ref, *docker_type_vars_ref]