---
- name: Set docker container facts
  set_fact:
    docker_container_vars: "{{ docker_container.vars }}" &docker_container_vars_ref
    default_docker_container_vars: "{{ default_docker_container[docker_container.name].vars | default({}) }}" &default_docker_container_vars_ref

- name: Import docker role container(s)
  import_role:
    name: traviss25.docker.docker_container_collection
    tasks_from: "{{ docker_container.name }}"
  vars:
    image: "{{ docker_container.image | default(default_docker_container[docker_container.name].image) }}"
    <<: [*default_docker_container_vars_ref, *docker_container_vars_ref]