---
- name: Import docker install role
  import_role:
    name: traviss25.docker.docker
    tasks_from: install
  vars:
    username: "{{ droplet.user_creds.username }}"

- name: Import docker role images(s)
  loop: "{{ droplet.docker_containers }}"
  include_role:
    name: traviss25.docker.docker
    tasks_from: image_pull
  vars:
    image: "{{ item.image }}"

- name: Import docker container task
  loop: "{{ droplet.docker_containers }}"
  include_role:
    name: traviss25.docker.docker
    tasks_from: container.yaml
  vars:
    name: "{{ item.name }}"
    from_collection: "{{ item.from_collection }}"
    image: "{{ item.image }}"
    action: "{{ item.action }}"
    vars: "{{ item.vars }}"
    params: "{{ item.params }}"

- name: Import docker compose task
  loop: "{{ droplet.docker_composes | default([]) }}"
  include_role:
    name: traviss25.docker.docker
    tasks_from: compose_service.yaml
  vars:
    name: "{{ item.name }}"
    from_collection: "{{ item.from_collection }}"
    action: "{{ item.action }}"
    vars: "{{ item.vars }}"
    params: "{{ item.params }}"
