---
- name: Create cockroach storage path
  file:
    state: directory
    path: "{{ storage_path }}"

- name: Set join cluster command fact
  set_fact:
    cockroachdb_command: "start --insecure --join={{ host }}"

- name: Set cockroachdb container facts
  set_fact:
    cockroachdb_container: &cockroachdb_container_ref
      name: cockroachdb
      hostname: cockroachdb
      restart_policy: always
      publish_all_ports: yes
      command: "{{ cockroachdb_command }}"
      mounts:
        - source: "{{ storage_path }}"
          target: /cockroach/cockroach-data

- name: Import container action task for cockroachdb
  import_task: container_action.yaml
  vars:
    action: "{{ action }}"
    image: "{{ image }}"
    params: *cockroachdb_container_ref

- name: Init cluster block
  when: cockroachdb_init_cluster and action == 'start'
  block:
    - name: Set init cluster command fact
      with_dict: "{{ cockroachdb_container }}"
      vars:
        new_item: "{'command': 'init --insecure --host={{ host }}'}"
      set_fact:
        cockroachdb_container: "{{ cockroachdb_container | combine(new_item, recursive=true) }}"
    - name: Init cockroachdb cluster
      import_task: container_action.yaml
      vars:
        action: "{{ action }}"
        image: "{{ image }}"
        params: *cockroachdb_container_ref
