---
- name: Set mount facts
  set_fact:
    mounts: []

- name: Single mode facts
  when: distributed_mode is not defined
  set_fact:
    command: "server {{ protocol }}://{{ hostname }}/data --console-address ':9001'"
    mounts: "{{ mounts + [combine({'source': storage_path, 'target': '/data'})] }}"

- name: Distributed mode block
  when: distributed_mode is defined
  block:
    - name: Distributed mode facts
      set_fact:
        command: |
          server {{ protocol }}://{{ hostname }}{1...{{ distributed_mode.num_of_hosts }}}/data{1...{{ distributed_mode.num_of_drives }}} \
          --console-address ':9001'

    - name: Loop storage paths
      loop: "{{ range(1, distributed_mode.num_of_drives + 1) }}"
      loop_control:
        index_var: idx
      vars:
        new_source: "{{ item }}{{ idx + 1 }}"
        new_target: "/data{{ idx + 1 }}"
      set_fact:
        mounts: "{{ mounts + [combine({'source': new_source, 'target', new_target})] }}"

- name: Import container action task
  import_task: container_action.yaml
  vars:
    action: "{{ action }}"
    image: "{{ image }}"
    params:
      name: minio
      hostname: minio
      restart_policy: always
      publish_all_ports: yes
      command: "{{ command }}"
      mounts: "{{ mounts }}"
