---
- name: Create prometheus storage path
  file:
    state: directory
    path: "{{ vars.storage_path }}"

- name: Import container action task for prometheus
  import_task: container_action.yaml
  vars:
    action: "{{ vars.action }}"
    params:
      name: prometheus
      hostname: prometheus
      image: "{{ vars.image }}"
      restart_policy: always
      publish_all_ports: yes
      command:
        - --web.enable-lifecycle
        - --storage.tsdb.path=/etc/prometheus/data/
        - --config.file=/etc/prometheus/prometheus.yml
      mounts:
        - source: "{{ vars.storage_path }}"
          target: /etc/prometheus/data/
