---
- name: Import container action task for redis
  import_task: container_action.yaml
  vars:
    action: "{{ vars.action }}"
    params:
      name: redis
      hostname: redis
      image: "{{ vars.image }}"
      restart_policy: always
      publish_all_ports: yes
      command:
        - redis-server
        - --appendonly=yes
      mounts:
        - source: "{{ vars.storage_path }}"
          target: /data
