---
- name: Set base corefile facts
  set_fact:
    file_state: "{{ file_state | default(corefile_defaults.file_state) }}"
    root_dir: "{{ root_dir | default(corefile_defaults.root_dir) }}"

- name: Set corefile facts
  set_fact:
    corefile: "{{ root_dir }}/Corefile"

- name: Delete existing corefile if exists
  when: file_state == 'create' or file_state == 'delete'
  file:
    state: absent
    path: "{{ corefile }}"

- name: Use template to generate Corefile
  when: file_state == 'create'
  template:
    src: corefile.j2
    dest: "{{ corefile }}"
    mode: 0777
  vars:
    server_blocks: "{{ records }}"

- name: Append corefile block
  when: file_state == 'append'
  block:
    - name: Generate random file name
      set_fact:
        tmp_file_name: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

    - name: Create temp dir
      file:
        state: directory
        path: "{{ root_dir }}/tmp"
      register: tmp_dir

    - name: Set append corefile facts
      set_fact:
        tmp_file_path: "{{ (tmp_dir.path, tmp_file_name) | path_join }}"

    - name: Use template to generate temp corefile
      template:
        src: corefile.j2
        dest: "{{ tmp_file_path }}"
        mode: 0777

    - name: Append to core file
      shell: "cat {{ tmp_corefile.path }} >> {{ corefile }}"

    - name: Delete temp file
      file:
        state: absent
        path: "{{ tmp_corefile.path }}"
