---
- name: Set base host facts
  set_fact:
    host_file_path: "{{ (root_dir, host_file) | path_join }}"

- name: Make host directory
  file:
    path: "{{ root_dir }}"
    state: directory
    mode: 0600

- name: Delete existing hosts file
  when: file_state == 'create' or file_state == 'delete'
  file:
    path: "{{ host_file_path }}"
    state: absent

- name: Create hosts file
  when: file_state != 'delete'
  file:
    path: "{{ host_file_path }}"
    state: touch

- name: Use template to generate host file
  when: file_state == 'create'
  template:
    src: host.j2
    dest: "{{ host_file_path }}"
    mode: 0600
  vars:
    records: "{{ records }}"

- name: Append to end of host file
  when: file_state == 'append'
  loop: "{{ records }}"
  blockinfile:
    state: present
    path: "{{ host_file_path }}"
    block: "{{ item.ip }} {{ item.host }}"

- name: Replace host file
  when: file_state == 'update'
  loop: "{{ records }}"
  replace:
    path: "{{ host_file_path }}"
    regexp: "^{{ item.ip }} {{ item.host }}$"
    replace: "{{ item.change_to_ip }} {{ item.change_to_host }}"
