---
- name: Import corefile task
  import_tasks: corefile.yml
  vars:
    file_state: "{{ corefile.file_state }}"
    root_dir: "{{ corefile.root_dir }}"
    records: "{{ corefile.records }}"

- name: Import host file task
  when: hosts is defined
  loop: "{{ hosts }}"
  include_tasks: host_file.yml
  vars:
    file_state: "{{ item.file_state }}"
    root_dir: "{{ item.root_dir }}"
    host_file: "{{ item.host_file }}"
    records: "{{ item.records }}"