---
storage_path_options: &storage_path_options_ref
  storage_path:
    type: str
    required: true
    description: Absolute path to directory to store data on host

config_file_options: &config_file_options_ref
  config_file:
    type: str
    required: true
    description: Absolute path to main config file on host

config_dir_options: &config_dir_options_ref
  config_dir:
    type: str
    required: true
    description: Absolute path to root dir where multiple config files reside

docker_container_options: &docker_container_options_ref
  action:
    type: str
    default: start
    description: Determine what action to perform on docker container
    choices:
      - start
      - stop
      - restart

alertmanager_options: &alertmanager_options_ref
  root_var:
    type: dict
    required: true
    description: Generic vars for alert manager
    options:
      <<: [*docker_container_options_ref, *config_file_options_ref]

coredns_options: &coredns_options_ref
  root_var:
    type: dict
    required: true
    description: Generic vars for coredns
    options:
      <<: [*docker_container_options_ref, *config_file_options_ref]

cockroachdb_options: &cockroachdb_options_ref
  root_var:
    type: dict
    required: true
    description: Generic vars for cockroachdb
    options:
      start_command:
        type: list
        elements: str
        required: true
        description: Command line arguments to use against container to start
      init_command:
        type: list
        elements: str
        description: Command line arguments to use against container to init cluster
      <<: [*docker_container_options_ref, *storage_path_options_ref]

cockroachdb_certs_options: &cockroachdb_certs_options_ref
  root_var:
    type: dict
    required: true
    description: Generic vars for cockroachdb cert creation
    options:
      ca:
        type: dict
        description: Settings for cockroach node that generate CA
        options:
          cert_dir:
            type: str
            default: /etc/cockroachdb/ca/certs
            description: Root directory to store cockroachdb certs
          key_dir:
            type: str
            default: /etc/cockroachdb/ca/key
            description: Root directory to store cockroachdb key
          overwrite_ca_if_exists:
            type: bool
            default: false
            description: Determines whether to overwrite ca if one is already generated
      client:

      hosts:
        type: list
        required: true
        elements: str
        description: List of FQDNs or IPs that will be connected to cockroach cluster

minio_options: &minio_options_ref
  root_var:
    type: dict
    required: true
    description: Generic vars for minio
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref]
      hostname:
        type: str
        required: true
        description: Name of host to start server on
      protocol:
        type: str
        required: true
        description: Determines what protocol to use connect other nodes
        choices:
          - http
          - https
      distributed_mode:
        type: dict
        description: Object for settings on distributed mode for minio
        options:
          num_of_drives:
            type: int
            required: true
            description: Number of drives to attach to each node
          num_of_hosts:
            type: int
            required: true
            description: Number of hosts apart of cluster

node_exporter_options: &node_exporter_options_ref
  root_var:
    type: dict
    required: true
    description: Generic vars for node exporter
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref]

prometheus_options: &prometheus_options_ref
  root_var:
    type: dict
    required: true
    description: Generic vars for prometheus
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref, *config_dir_options_ref]

grafana_options: &grafana_options_ref
  root_var:
    type: dict
    required: true
    description: Generic vars for grafana
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref]

redis_options: &redis_options_ref
  root_var:
    type: dict
    required: true
    description: Generic vars for redis
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref]

argument_specs:
  alertmanager:
    short_description: Docker container actions for alert manager
    options: *alertmanager_options_ref

  alertmanager_preflight:
    short_description: Alertmanager preflight
    options: *alertmanager_options_ref

  coredns:
    short_description: Docker container actions for coredns
    options: *coredns_options_ref

  coredns_preflight:
    short_description: Coredns preflight
    options: *coredns_options_ref

  cockroachdb:
    short_description: Docker container actions for cockroachdb
    options: *cockroachdb_options_ref

  cockroachdb_preflight:
    short_description: Cockroachdb preflight
    options: *cockroachdb_options_ref

  minio:
    short_description: Docker container actions for minio
    options: *minio_options_ref

  minio_preflight:
    short_description: Minio preflight
    options: *minio_options_ref

  node_exporter:
    short_description: Docker container actions for node exporter
    options: *node_exporter_options_ref

  node_exporter_preflight:
    short_description: Node exporter preflight
    options: *node_exporter_options_ref

  prometheus:
    short_description: Docker container actions for prometheus
    options: *prometheus_options_ref

  prometheus_preflight:
    short_description: Prometheus preflight
    options: *prometheus_options_ref

  grafana:
    short_description: Docker container actions for grafana
    options: *grafana_options_ref

  grafana_preflight:
    short_description: Grafana preflight
    options: *grafana_options_ref

  redis:
    short_description: Docker container actions for redis
    options: *redis_options_ref

  redis_preflight:
    short_description: Redis preflight
    options: *redis_options_ref
