---
- name: Generate node cert/key
  uri:
    <<: *base_vault_uri_settings_ref
    url: "{{ base_url }}{{ root_var.vault.int_pki_mount_point }}/issue/{{ root_var.vault.issue_role }}"
    body: "{{ root_var.node_cert_request }}"
  register: cockroachdb_node_cert_res

- name: Generate user cert/key
  uri:
    <<: *base_vault_uri_settings_ref
    url: "{{ base_url }}{{ root_var.vault.int_pki_mount_point }}/issue/{{ root_var.vault.issue_role }}"
    body: "{{ root_var.client_cert_request }}"
  register: cockroachdb_user_cert_res