---
- name: Set facts
  set_fact:
    mkcert_path: /usr/local/bin/mkcert
    cert_path: "{% if droplet.ca.cert %}{{ droplet.ca.cert.file_path }}{% else %}{{ ca_droplet_defaults.cert.file_path }}% endif %}"
    cert_file: "{% if droplet.ca.cert %}{{ droplet.ca.cert.file_name }}{% else %}{{ ca_droplet_defaults.cert.file_name }}{% endif %}"

- name: Import create user role
  import_role:
    name: traviss25.util.user
    import_tasks: create
  vars:
    username: "{{ droplet.user_creds.username }}"
    password: "{{ droplet.user_creds.password }}"
    groups: "{{ droplet.user_creds.groups }}"

- name: Verify if mkcert is already installed
  stat:
    path: "{{ mkcert_path }}"
  register: mkcert_bin

- name: Install ca server packages block
  when: not mkcert_bin.stat.exists
  block:
    - name: Install ca packages
      apt:
        pkg:
          - libnss3-tools

    - name: Download mkcert and install
      ansible.builtin.get_url:
        url: https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64
        dest: "{{ mkcert_path }}"
        mode: "777"

- name: Create cert directory path
  file:
    path: "{{ cert_path }}"
    state: directory

- name: Run mkcert program
  shell: "mkcert -cert-file={{ cert_path }}{{ cert_file }} {% for domain in droplet.ca.domains %} {{ domain }} {% endfor %}"
