---
- name: Install vagrant if not installed
  when: 'vagrant' not in ansible_facts.packages
  become: true
  shell: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main
    apt update
    apt install vagrant

- name: Install vagrant plugin for virtualbox
  when: vm_provider == 'virtualbox'
  shell: vagrant plugin install vagrant-vbguest

- name: Install vagrant plugin for libvirt
  when: vm_provider == 'libvirt'
  shell: vagrant plugin install vagrant-libvirt