---
- name: Set provider install facts
  set_fact:
    vm_provider: "{{ vm_provider | default(vm_provider_install_defaults.vm_provider) }}"

- name: Update repository cache
  apt:
    update_cache: yes

- name: Install virtualbox
  when: vm_provider == 'virtualbox'
  apt:
    pkg:
      - virtualbox-qt

- name: Install libvirt
  when: vm_provider == 'libvirt'
  block:
    - name: Download libvirt packages
      apt:
        pkg:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - libvirt-dev
          - ruby-libvirt
          - ebtables
          - dnsmasq-base
          - libxslt-dev
          - libxml2-dev
          - zlib1g-dev
          - ruby-dev
          - libguestfs-tools
          - virt-manager
