---
base_ca_options: &base_ca_options_ref
  cert:
    type: dict
    description: Settings to store the host cert
    options:
      dir_path:
        type: str
        default: /etc/ssl/ca-certs
        description: Root directory path where to store certs
      filename:
        type: str
        default: ca.pem
        description: Filename of cert
  key:
    type: dict
    description: Settings to store the host private key
    options:
      dir_path:
        type: str
        default: /etc/ssl/ca-keys
        description: Root directory path where to store keys
      filename:
        type: str
        default: ca.key
        description: Filename of private key

server_options: &server_options_ref
  <<: *base_ca_options_ref

client_options: &client_options_ref
  <<: *base_ca_options_ref
  subject_alt_names:
    type: list
    required: true
    elements: str
    description: List of names to represent current host
  ca_server:
    type: dict
    required: true
    description: Object settings for CA server
    options:
      <<: *base_ca_options_ref
      ip:
        type: str
        required: true
        description: IP of CA server to get cert signed by

argument_specs:
  server:
    short_description: Sets up CA server
    description: Sets up CA server so other droplets can use it for ssl
    options: *server_options_ref

  server_preflight:
    short_description: Server preflight
    options: *server_options_ref

  client:
    short_description: Sets up client for CA
    description: Sets up client to make a CSR to our CA
    options: *client_options_ref

  client_preflight:
    short_description: Client preflight
    options: *client_options_ref
