---
all_defaults:
  base_ansible_install_path: ~/.ansible/collections/ansible_collections
  vm_providers:
    - virtualbox
    - libvirt
  docker_container:
    grafana:
      image: grafana/grafana:9.0.4
      vars:
        action: start
        storage_path: /mnt/storage/grafana
    cockroachdb:
      image: cockroachdb/cockroach:v22.1.3
      vars:
        action: start
        storage_path: /mnt/storage/cockroachdb
    prometheus:
      image: prom/prometheus:v2.37.0
      vars:
        action: start
        storage_path: /mnt/storage/promethues
    minio:
      image: minio/minio:RELEASE.2022-06-11T19-55-32Z
      vars:
        action: start
    mariadb:
      image: bitnami/mariadb:10.1.47
      vars:
        action: start
        storage_path: /mnt/storage/mariadb
    jasperreports:
      image: bitnami/jasperreports:6.4.3
      vars:
        action: start
        storage_path: /mnt/storage/jasperreports
    node_exporter:
      image: prom/node-exporter:v1.3.1
      vars:
        action: start
        storage_path: /mnt/storage/node_exporter
    alert_manager:
      image: prom/alertmanager:v0.24.0
      vars:
        action: start
        storage_path: /mnt/storage/alert_manager
    redis:
      image: redis:6.2.4
      vars:
        action: start

all_run_types:
  - test
  - local
  - digitalocean

all_fstype_choices:
  - btrfs
  - ext2
  - ext3
  - ext4
  - ext4dev
  - f2fs
  - lvm
  - ocfs2
  - reiserfs
  - xfs
  - vfat
  - swap
  - ufs
