---
cert_options: &cert_options_ref
  cert:
    type: dict
    description: Settings for cert

storage_path_options: &storage_path_options_ref
  storage_path:
    type: str
    required: true
    description: Default storage directory docker container writes to on host

minio_options: &minio_options_ref
  hostname:
    type: str
    required: true
    description: Name of host to start server on
  protocol:
    type: str
    required: true
    description: Determines what protocol to use connect other nodes
    choices:
      - http
      - https

docker_container_options: &docker_container_options_ref
  image:
    type: str
    required: true
    description: Docker image to use
  action:
    type: str
    required: true
    default: start
    description: Determine what action to perform on docker container
    choices:
      - start
      - stop
      - restart

argument_specs:
  alert_manager:
    short_description: Docker container actions for alert manager
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref]

  cockroachdb:
    short_description: Docker container actions for cockroachdb
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref]

  minio:
    short_description: Docker container actions for minio
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref]
      distributed_mode:
        type: dict
        description: Object for settings on distributed mode for minio
        options:
          num_of_drives:
            type: int
            required: true
            description: Number of drives to attach to each node
          num_of_hosts:
            type: int
            required: true
            description: Number of hosts apart of cluster

  node_exporter:
    short_description: Docker container actions for node exporter
    options: *docker_container_options_ref

  prometheus:
    short_description: Docker container actions for prometheus
    options: *docker_container_options_ref

  grafana:
    short_description: Docker container actions for grafana
    options:
      <<: [*docker_container_options_ref]

  redis:
    short_description: Docker container actions for redis
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref]
