---
- name: Set cockroachdb certs facts
  set_fact:
    ca:
      cert_dir: "{{ root_var.ca.cert_dir | default(cockroachdb_certs_defaults.ca.cert_dir) }}"
      key_dir: "{{ root_var.ca.key_dir | default(cockroachdb_certs_defaults.ca.key_dir) }}"
      overwrite_ca_if_exists: "{{ root_var.ca.key_dir | default(cockroachdb_certs_defaults.ca.overwrite_ca_if_exists) }}"

- name: CA block
  when: root_var.ca is defined
  block:
    - name: Create cockroach cert dir
      file:
        state: directory
        path: "{{ ca.cert_dir }}"
        mode: 0600

    - name: Create cockroach key dir
      file:
        state: directory
        path: "{{ ca.key_dir }}"
        mode: 0600

    - name: Determine if ca cert already exists
      stat:
        path: "{{ ca.key_dir }}/ca.crt"

    - name: Create cockroachdb cert
      community.docker.docker_container:
        auto_remove: true
        image: "cockroachdb/cockroach:{{ all_cockroachdb_defaults.image_version }}"
        command: "cert create-ca"

- name: Set cockroachdb container facts
  set_fact:
    cockroachdb_container_params: &cockroachdb_container_params_ref
      name: cockroachdb_
      hostname: cockroachdb
      image: "cockroachdb/cockroach:{{ all_cockroachdb_defaults.image_version }}"
      restart_policy: always
      publish_all_ports: yes
      command: "{{ root_var.start_command }}{% if root_var.init_command and root_var.action == 'start' %} && {{ root_var.init_command }}{% endif %}"
      mounts:
        - source: "{{ root_var.storage_path }}"
          target: /cockroach/cockroach-data