---
- name: Create grafana storage path
  file:
    state: directory
    path: "{{ root_var.storage_path }}"

- name: Set grafana container facts
  set_fact:
    grafana_params: &grafana_params_ref
      name: grafana
      hostname: grafana
      image: grafana/grafana:9.0.5
      restart_policy: always
      publish_all_ports: yes
      mounts:
        - source: "{{ root_var.storage_path }}"
          target: /var/lib/grafana

- name: Start container
  when: root_var.action == 'start'
  community.docker.docker_container:
    <<: *grafana_params_ref

- name: Restart container
  when: root_var.action == 'restart'
  community.docker.docker_container:
    state: started
    restart: yes
    <<: *grafana_params_ref

- name: Stop container
  when: root_var.action == 'stop'
  community.docker.docker_container:
    state: stopped
    <<: *grafana_params_ref