---
- name: Create redis storage path
  file:
    state: directory
    path: "{{ vars.storage_path }}"

- name: Set redis facts
  set_fact:
    redis_params: &redis_params_ref
      name: redis
      hostname: redis
      image: redis:6.2.4
      restart_policy: always
      publish_all_ports: yes
      command:
        - redis-server
        - --appendonly=yes
      mounts:
        - source: "{{ vars.storage_path }}"
          target: /data

- name: Start container
  when: vars.action == 'start'
  community.docker.docker_container:
    <<: *redis_params_ref

- name: Restart container
  when: vars.action == 'restart'
  community.docker.docker_container:
    state: started
    restart: yes
    <<: *redis_params_ref

- name: Stop container
  when: vars.action == 'stop'
  community.docker.docker_container:
    state: stopped
    <<: *redis_params_ref