---
- name: Set vault facts
  set_fact:
    vault_params: &vault_params_ref
      name: vault
      image: vault:1.11.4
      hostname: vault
      restart_policy: always
      publish_all_ports: yes
      command:
        - vault
        - server
        - -config=/etc/vault
      mounts:
        - source: "{{ root_var.config_dir }}"
          target: /etc/vault

- name: Start container
  when: root_var.action == 'start'
  community.docker.docker_container:
    <<: *vault_params_ref

- name: Restart container
  when: root_var.action == 'restart'
  community.docker.docker_container:
    state: started
    restart: yes
    <<: *vault_params_ref

- name: Stop container
  when: root_var.action == 'stop'
  community.docker.docker_container:
    state: stopped
    <<: *vault_params_ref