---
- name: Set up dev enviroment
  hosts: localhost
  gather_facts: true

  pre_tasks:
    - name: Assert import_file is defined
      assert:
        that: import_file is defined
      fail_msg: Variable "import_file" is not defined

  tasks:
    - name: Import vars from file
      include_vars:
        file: "{{ import_file }}"
        name: file_vars

    - name: Verify droplets
      loop: "{{ file_vars.droplets }}"
      include_role:
        name: traviss25.util.setup
        tasks_from: droplet
      vars:
        execute: false
        droplet: "{{ item }}"

    - name: Install virtualbox if not installed
      when: 'virtualbox-qt' not in ansible_facts.packages
      apt:
        name: virtualbox-qt

    - name: Install vagrant if not installed
      when: 'vagrant' not in ansible_facts.packages
      import_role:
        name: setup
        tasks_from: vagrant_install

    - name: Verify vagrant setup
      import_role:
        name: setup
        tasks_from: vagrant_setup
      vars:
        execute: false
        box: "{{ file_vars.vagrant.box }}"
        project_root: "{{ file_vars.vagrant.project_root }}"
        file_content: "{{ file_vars.vagrant.file_content }}"

    - name: Setup vagrant
      import_role:
        name: setup
        tasks_from: vagrant_setup
      vars:
        box: "{{ file_vars.vagrant.box }}"
        project_root: "{{ file_vars.vagrant.project_root }}"
        file_content: "{{ file_vars.vagrant.file_content }}"

    - name: Import ssh setup role
      loop: "{{ file_vars.droplets }}"
      include_role:
        name: traviss25.util.ssh
        tasks_from: pass_key
      vars:
        ip: "{{ item.ip }}"
        user: "{{ item.user_creds.username }}"
        password: "{{ item.user_creds.password }}"

    - name: Import update droplet file role
      loop: "{{ file_vars.droplets | subelements('host_file_list') }}"
      include_role:
        name: system_util
        tasks_from: update_droplets_file
        apply:
          delegate_to: "{{ item.0.ip }}"
          become: true
          remote_user: "{{ item.0.user }}"
      vars:
        ip: "{{ item.1.ip }}"
        fqdn: "{{ item.1.fqdn }}"
        hostname: "{{ item.1.hostname }}"

    
