---
- name: Foo
  hosts: localhost

  tasks:
    - become: true
      block:
        - name: Import libvirt install
          import_role:
            name: setup
            tasks_from: vm_provider_install
          vars:
            vm_provider: libvirt

    # - name: Set dev facts
    #   set_fact:
    #     ansible_root_dir: "{{ lookup('env', 'ANSIBLE_ROOT') }}"

    # - name: Import vars from file
    #   include_vars:
    #     file: "{{ import_file }}"
    #     name: file_vars

    # - name: Import droplet argument specs
    #   include_vars:
    #     name: droplet_arg_specs
    #     file: "{{ all_defaults.base_ansible_install_path }}/traviss25/util/roles/setup/meta/argument_specs.yaml"

    # - name: Import vagrant argument specs
    #   include_vars:
    #     name: vagrant_arg_specs
    #     file: "{{ all_defaults.base_ansible_install_path }}/traviss25/dev/roles/setup/meta/argument_specs.yaml"

    # - name: Import ssh argument specs
    #   include_vars:
    #     name: ssh_arg_specs
    #     file: "{{ all_defaults.base_ansible_install_path }}/traviss25/util/roles/ssh/meta/argument_specs.yaml"

    # - name: Import host file argument specs
    #   include_vars:
    #     name: host_file_arg_specs
    #     file: "{{ all_defaults.base_ansible_install_path }}/traviss25/dev/roles/system_util/meta/argument_specs.yaml"

    # - name: Import dev setup
    #   include_vars:
    #     name: setup_test_arg_specs
    #     file: "{{ all_defaults.base_ansible_install_path }}/traviss25/dev/roles/setup/meta/argument_specs.yaml"

    # - name: Display stuff here
    #   debug:
    #     msg: "{{ setup_test_arg_specs['argument_specs']['test']['options'] }}"

    # - name: Testing argument spec
    #   validate_argument_spec:
    #     argument_spec: "{{ setup_test_arg_specs['argument_specs']['test']['options'] }}"
    #     provided_arguments:
    #       vm_provider: invalid

    # - name: Verify droplets setup
    #   loop: "{{ file_vars.droplets }}"
    #   validate_argument_spec:
    #     argument_spec: "{{ droplet_arg_specs['argument_specs']['droplet']['options'] }}"
    #     provided_arguments:
    #       droplet: "{{ item }}"
    #       default_docker_container: "{{ all_defaults.docker_container }}"
