---
droplet_options: &droplet_options_ref
  droplet:
    type: dict
    required: true
    description: The droplet that will be set up
    options:
      ip:
        type: str
        required: true
        description: IP of droplet
      hostname:
        type: str
        required: true
        description: Hostname of droplet
      dns:
        type: dict
        description: Passthough
      ca:
        type: dict
        description: Passthough
      vagrant:
        type: dict
        description: Passthough
      user_creds:
        type: dict
        required: true
        description: User creds for droplet
        options:
          username:
            type: str
            required: true
            description: Username that will be created for droplet
          password:
            type: str
            required: true
            description: Password for user that will be created for droplet
          groups:
            type: list
            required: true
            description: List of groups that the user will be apart of
      mounts:
        type: list
        elements: dict
        description: List of dicts that determine what device to mount and where
        options:
          mount_point:
            type: str
            required: true
            description: Mount point to mount device
          device:
            type: str
            required: true
            description: Device to mount
          fstype:
            type: str
            required: true
            description: File system type to apply to disk
      docker_composes:
        type: list
        elements: dict
        description: Passthough
      docker_containers:
        type: list
        elements: dict
        required: true
        description: Passthough

argument_specs:
  droplet:
    short_description: Creates droplet
    description: Creates droplet based on settings passed
    options: *droplet_options_ref
  droplet_preflight:
    short_description: Droplet preflight
    options: *droplet_options_ref
