---
- name: Set compose action facts
  set_fact:
    docker_compose_params: "{{ params }}" &docker_compose_params_ref

- name: Start compose
  when: action == 'start'
  community.docker.docker_compose:
    project_name: "{{ name }}"
    <<: *docker_compose_params_ref

- name: Restart compose
  when: action == 'restart'
  community.docker.docker_compose:
    project_name: "{{ name }}"
    restarted: yes
    <<: *docker_compose_params_ref

- name: Stop compose
  when: action == 'stop'
  community.docker.docker_compose:
    project_name: "{{ name }}"
    stopped: yes
    <<: *docker_compose_params_ref
