---
- name: Set container action facts
  set_fact:
    docker_container_params: &docker_container_params_ref 
      "{{ params }}" 

- name: Start container
  when: action == 'start'
  community.docker.docker_container:
    name: "{{ name }}"
    image: "{{ image }}"
    <<: *docker_container_params_ref

- name: Restart container
  when: action == 'restart'
  community.docker.docker_container:
    name: "{{ name }}"
    image: "{{ image }}"
    state: started
    restart: yes
    <<: *docker_container_params_ref

- name: Stop container
  when: action == 'stop'
  community.docker.docker_container:
    name: "{{ name }}"
    image: "{{ image }}"
    state: stopped
    <<: *docker_container_params_ref