---
- name: Start container
  when: action == 'start'
  community.docker.docker_container:
    state: started
    <<: "{{ container_params }}"

- name: Restart container
  when: action == 'restart'
  community.docker.docker_container:
    state: started
    restart: yes
    <<: "{{ container_params }}"

- name: Stop container
  when: action == 'stop'
  community.docker.docker_container:
    state: stopped
    <<: "{{ container_params }}"