---
- name: Update repositories
  apt:
    update_cache: yes

- name: Gather the package facts
  package_facts:
    manager: auto

- name: Install docker and deps
  become: true
  when: "{{ ansible_facts.packages['docker-ce'] | length == 0 }}"
  block:
    - name: Install package dependencies
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Create key ring dir
      file:
        state: directory
        path: /etc/apt/keyrings

    - name: Download and apply gpg
      shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Add repository to apt sources
      shell:
        cmd: |
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update repositories
      apt:
        update_cache: yes

    # Docker version: 5:20.10.17~3-0~ubuntu-focal

    - name: Install docker packages
      apt:
        pkg:
          - "docker-ce={{ docker_version }}"
          - "docker-ce-cli={{ docker_version }}"

    - name: Create docker group
      shell:
        cmd: groupadd docker

    - name: Add user to docker group
      when: username is defined
      shell:
        cmd: usermod -aG docker "{{ username }}"

- name: Docker already installed
  when: "{{ ansible_facts.packages['docker-ce'] | length > 0 }}"
  debug:
    msg: Docker already installed
