---
- name: Digital Ocean Setup
  hosts: localhost
  vars_files:
    - ../../../vars/providers/digitalocean/secrets.yaml

  tasks:
    - name: Setting base digital ocean facts
      set_fact:
        pb_timeout: "{{ timeout | default(30) }}"
        pb_oauth_token: "{{ oauth_token }}"