---
docker_container_collection_defaults:
  grafana:
    image: grafana/grafana:9.0.4
    action: start
    vars:
      storage_path: /mnt/storage/grafana
  cockroachdb:
    image: cockroachdb/cockroach:v22.1.3
    action: start
    vars:
      storage_path: /mnt/storage/cockroachdb
  prometheus:
    image: prom/prometheus:v2.37.0
    action: start
    vars:
      storage_path: /mnt/storage/promethues
  minio:
    image: minio/minio:RELEASE.2022-06-11T19-55-32Z
    action: start
  mariadb:
    image: bitnami/mariadb:10.1.47
    action: start
    vars:
      storage_path: /mnt/storage/mariadb
  jasperreports:
    image: bitnami/jasperreports:6.4.3
    action: start
    vars:
      storage_path: /mnt/storage/jasperreports
  node_exporter:
    image: prom/node-exporter:v1.3.1
    action: start
    vars:
      storage_path: /mnt/storage/node_exporter
  alert_manager:
    image: prom/alertmanager:v0.24.0
    action: start
    vars:
      storage_path: /mnt/storage/alert_manager
  redis:
    image: redis:6.2.4
    action: start