---
docker_action: &docker_action_ref
  type: "str"
  required: true
  default: start
  choices:
    - start
    - stop
    - restart
    - configure
  description: Determine what action to perform on docker container

storage_path_options: &storage_path_options_ref
  storage_path:
    type: "str"
    required: true
    description: Default storage directory docker container writes to on host

docker_container_options: &docker_container_options_ref
  image:
    type: "str"
    required: true
    description: Docker image to use
  docker_action:
    <<: *docker_action_ref

argument_specs:
  cockroachdb:
    short_description: Docker container actions for cockroachdb
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref]
  minio:
    short_description: Docker container actions for minio
    options:
      filesystem_mode:
        type: dict
        description: Option to use when setting up one node and one drive
        options:
          drive_name:
            type: str
            required: true
            description: Name of the drive to mount at /mnt/<drive_name>
      distributed_mode:
        type: dict
        description: Options to use when setting up multiple nodes/drives
        options:
          protocol:
            type: str
            required: true
            description: Determines what protocol to use connect other nodes
            choices:
              - http
              - https
          hostname:
            type: str
            required: true
          num_of_drives:
            type: int
            required: true
          num_of_hosts:
            type: int
            required: true
          <<: [*docker_container_options_ref, *storage_path_options_ref]
  prometheus:
    short_description: Docker container actions for prometheus
    options:
      <<: *docker_container_options_ref
      config_file:
        type: "str"
        required: true
        description: Config file for prometheus
  container_action:
    short_description: Determines docker container action
    options:
      docker_action:
        <<: *docker_action_ref
      container_params:
        type: dict
        required: true
        description: Options for the community.docker.docker_container module
