---
docker_action: &docker_action_ref
  type: str
  required: true
  default: start
  description: Determine what action to perform on docker container
  choices:
    - start
    - stop
    - restart

storage_path_options: &storage_path_options_ref
  storage_path:
    type: str
    required: true
    description: Default storage directory docker container writes to on host

minio_options: &minio_options_ref
  hostname:
    type: str
    required: true
    description: Name of host to start server on
  protocol:
    type: str
    required: true
    description: Determines what protocol to use connect other nodes
    choices:
      - http
      - https

docker_container_options: &docker_container_options_ref
  image:
    type: str
    required: true
    description: Docker image to use
  action:
    <<: *docker_action_ref

argument_specs:
  alert_manager:
    short_description: Docker container actions for alert manager
    options:
      <<: [*docker_container_options_ref, *minio_options_ref]
  cockroachdb:
    short_description: Docker container actions for cockroachdb
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref]
  minio:
    short_description: Docker container actions for minio
    options:
      filesystem_mode:
        <<: *minio_options_ref
      distributed_mode:
        type: dict
        description: Options to use when setting up multiple nodes/drives
        options:
          num_of_drives:
            type: int
            required: true
          num_of_hosts:
            type: int
            required: true
          <<: [*docker_container_options_ref, *minio_options_ref]
  node_exporter:
    short_description: Docker container actions for node exporter
    options:
      <<: [*docker_container_options_ref, *storage_path_options_ref]
  prometheus:
    short_description: Docker container actions for prometheus
    options:
      <<: *docker_container_options_ref
