---
docker_action: &docker_action_ref
  type: str
  required: true
  default: start
  description: Determine what action to perform on docker container
  choices:
    - start
    - stop
    - restart

argument_specs:
  install:
    short_description: Installs docker
    description: Installs docker on box and will skip if already on box
    options:
      username:
        type: str
        description: Username to add to docker group that is created
      docker_version:
        type: str
        default: 5:20.10.17~3-0~ubuntu-focal

  container_action:
    short_description: Determines docker container action
    options:
      action: *docker_action_ref
      container_params:
        type: dict
        required: true
        description: Options for the community.docker.docker_container module

  image_pull:
    short_description: Pulls docker image
    description: Pulls docker image based on docker image name given
    options:
      image:
        type: str
        required: true
        description: Name of docker image to pull
