---
project_root: &project_root_ref
  type: str
  required: true
  description: Root project folder to store vagrant info

disk_options: &disk_options_ref
  name:
    type: str
    required: true
    description: Name of disk
  size:
    type: int
    required: true
    description: Size of disk in GB

vm_name: &vm_name_ref
  type: str
  required: true
  description: Name of vm which should be unique

argument_specs:
  setup:
    short_description: Sets up libvirt environment
    description: Sets up libvirt environment if that is the chosen provider in playbook
    options:
      vm_name: *vm_name_ref
      project_root: *project_root_ref
      disks:
        type: list
        elements: dict
        description: List of disk objects to create disks for libvirt
        options: *disk_options_ref

  disk:
    short_description: Creates/attaches disks for libvirt vm
    options:
      vm_name: *vm_name_ref
      project_root: *project_root_ref
      disk: *disk_options_ref
