---
- name: Create private key directory
  file:
    path: "{{ public_key_path.dir_path }}"
    state: directory

- name: Create public key directory
  file:
    path: "{{ private_key_path.dir_path }}"
    state: directory

- name: Set absolute filepaths
  set_fact:
    wg_key_public_key_path: "{{ (public_key_path.dir_path, public_key_path.filename) | path_join }}"
    wg_key_private_key_path: "{{ (private_key_path.dir_path, private_key_path.filename) | path_join }}"

- name: Generate private key
  shell: wg genkey | tee "{{ wg_key_private_key_path }}"

- name: Change file mode of private key
  file:
    path: "{{ wg_key_private_key_path }}"
    mode: 0600

- name: Generate public key
  shell: "cat {{ wg_key_private_key_path }} | wg pubkey | tee {{ wg_key_public_key_path }}"

- name: Change file mode of public key
  file:
    path: "{{ wg_key_public_key_path }}"
    mode: 0644