---
- name: Set base terraform preflight facts
  set_fact:
    tf_backend_config: {}
    tf_root_path: ''
    tf_current_state_file: ''
    tf_variable_files: []
    tf_workspace: "{{ workspace | default(main_defaults.workspace) }}"
    pac_tf_state_file: "{{ lookup('env', 'PAC_TF_STATE_FILE') }}"
    pac_tf_workspace_dir: "{{ lookup('env', 'PAC_TF_WORKSPACE_DIR') }}"
    ssh_file_path: "{{ lookup('env', 'SSH_FILE_PATH') }}"

- name: Local workspace block
  when: tf_workspace == 'local'
  block:
    - name: Assert local_vars set
      assert:
        that: local_vars is defined
        fail_msg: Variable 'local_vars' must be set when workspace == 'local'

    - name: Assert environment variables are set
      assert:
        that: 
          - pac_tf_state_file is defined
          - pac_tf_state_file != ""
          - pac_tf_workspace_dir is defined
          - pac_tf_workspace_dir != ""
          - ssh_file_path is defined
          - ssh_file_path != ""
        fail_msg: Environment variables "PAC_TF_STATE_FILE", "SSH_FILE_PATH" and "PAC_TF_WORKSPACE_DIR" must be set

- name: Assert remote_vars set
  when: tf_workspace != 'local'
  assert:
    that: remote_vars is defined
    fail_msg: Variable 'remote_vars' must be set when tf_workspace != 'local'

- name: Set terraform preflight facts
  set_fact:
    tf_variables: "{% if remote_vars is defined %}{{ remote_vars }}{% else %}{{ local_vars }}{% endif %}"

- name: Import terraform plan task
  import_tasks: main.yml
  vars:
    state: planned
    workspace: "{{ tf_workspace }}"
    local_vars: "{{ tf_variables }}"
