---
- name: Generate node cert/key
  uri:
    <<: *base_vault_uri_settings_ref
    url: "{{ base_url }}{{ root_var.vault.int_pki_mount_point }}/issue/{{ root_var.vault.issue_role }}"
    body: "{{ root_var.node_cert_request }}"
  register: cockroachdb_node_cert_res

- name: Generate user cert/key
  uri:
    <<: *base_vault_uri_settings_ref
    url: "{{ base_url }}{{ root_var.vault.int_pki_mount_point }}/issue/{{ root_var.vault.issue_role }}"
    body: "{{ root_var.client_cert_request }}"
  register: cockroachdb_client_cert_res

- name: Write CA cert to cockroachdb directory
  copy:
    dest: "{{ root_var.cockroach_certs_dir }}/ca.crt"
    content: "{{ cockroachdb_node_cert_res['data']['issuing_ca'] }}"

- name: Write node cert to cockroachdb directory
  copy:
    dest: "{{ root_var.cockroach_certs_dir }}/node.crt"
    content: "{{ cockroachdb_node_cert_res['data']['certificate'] }}"

- name: Write node key to cockroachdb directory
  copy:
    dest: "{{ root_var.cockroach_certs_dir }}/node.key"
    content: "{{ cockroachdb_node_cert_res['data']['private_key'] }}"

- name: Write client cert to cockroachdb directory
  copy:
    dest: "{{ root_var.cockroach_certs_dir }}/client.{{ root_var.client_cert_request.common_name }}.crt"
    content: "{{ cockroachdb_client_cert_res['data']['certificate'] }}"

- name: Write client key to cockroachdb directory
  copy:
    dest: "{{ root_var.cockroach_certs_dir }}/client.{{ root_var.client_cert_request.common_name }}.key"
    content: "{{ cockroachdb_client_cert_res['data']['private_key'] }}"
