---
- name: Assert tag is in deploy settings
  when: preflight
  assert:
    that: tag in deploy_settings
  fail_msg: "Tag {{ tag }} not in deploy settings"

- name: Set deploy vars
  when: tag in deploy_settings and not preflight
  set_fact:
    deploy_vars: "{{ deploy_settings[tag] | combine({'ip': droplet.ip}) }}"

- when: tag == 'cockroachdb'
  block:
    - name: Update cert requests
      vars:
        node_cert_request: "{{ deploy_vars['node_cert_request'] | combine({'ip_sans': droplet.ip}) }}"
        client_cert_request: "{{ deploy_vars['client_cert_request'] | combine({'ip_sans': droplet.ip}) }}"
      set_fact:
        deploy_vars: "{{ deploy_vars | combine({'node_cert_request': node_cert_request, 'client_cert_request': client_cert_request}, recursive=true) }}"

    - name:
