---
- name: Install docker {% if preflight %}preflight{% endif %}
  import_role:
    name: traviss25.util.docker
    tasks_from: "{% if preflight %}install_preflight{% else %}install{% endif %}"
  vars:
    users:
      - "{{ droplet.user }}"

- name: Deploy tag {% if preflight %}preflight{% endif %}
  loop: "{{ droplet.tags }}"
  include_role:
    name: traviss25.pac.deploy
    tasks_from: "{% if preflight %}deploy_tag_preflight{% else %}deploy_tag{% endif %}"
  vars:
    droplet: "{{ droplet }}"
    deploy_tag_dict: "{{ deploy_tag_dict }}"
    tag: "{{ item }}"
    deploy_var_settings: "{{ deploy_var_settings }}"
