---
- name: Assert tag is in deploy settings
  when: preflight
  assert:
    that: tag in deploy_settings
  fail_msg: "Tag {{ tag }} not in deploy settings"

- name: Set deploy vars
  when: tag in deploy_settings and not preflight
  set_fact:
    deploy_vars: "{{ deploy_settings[tag] | combine({'ip': droplet.ip}) }}"

- when: tag == 'cockroachdb'
  block:
    - name: Update cockroachdb deploy vars
      vars:
        updates:
          node_cert_request: "{{ deploy_vars['node_cert_request'] | combine({'ip_sans': droplet.ip, 'common_name': 'node'}) }}"
          client_cert_request: "{{ deploy_vars['client_cert_request'] | combine({'ip_sans': droplet.ip, 'common_name': 'node'}) }}"
          vault: "{{ deploy_vars['vault'] | combine({'ip': deploy_tag_dict['vault'][0]}) }}"
      set_fact:
        deploy_vars: "{{ deploy_vars | combine(updates, recursive=true) }}"

    - name: Deploy cockroachdb
      import_role:
        name: traviss25.pac.deploy
        tasks_from: cockroachdb
      vars:
        root_var: "{{ deploy_vars }}"
