---
- name: Set node exporter facts
  set_fact:
    node_exporter_params: &node_exporter_params_ref
      name: node_exporter
      hostname: node_exporter
      image: prom/node-exporter:v1.3.1
      restart_policy: always
      publish_all_ports: yes
      command: |
        --path.procfs=/host/proc \
        --path.rootfs=/rootfs \
        --path.sysfs=/host/sys
      mounts:
        - source: /proc
          target: /host/proc:ro
        - source: /sys
          target: /host/sys:ro
        - source: /
          target: /rootfs:ro

- name: Start container
  when: root_var.action == 'start'
  community.docker.docker_container:
    <<: *node_exporter_params_ref

- name: Restart container
  when: root_var.action == 'restart'
  community.docker.docker_container:
    state: started
    restart: yes
    <<: *node_exporter_params_ref

- name: Stop container
  when: root_var.action == 'stop'
  community.docker.docker_container:
    state: stopped
    <<: *node_exporter_params_ref
