---
- name: Install lxd
  snap:
    name: lxd

- name: Add current user to lxd group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: lxd

- name: Set default preseed file content
  when: preseed_file is not defined
  set_fact:
    preseed_file_content: "{{ lookup('file', '../files/default_preseed.yml') }}"

- name: Set passed preseed file content
  when: preseed_file is defined
  set_fact:
    preseed_file_content: "{{ lookup('file', preseed_file) }}"

- name: Start basic lxd server
  become: true
  when: preseed_file is not defined
  shell: "lxd init --preseed < {{ preseed_file }}"