---
- name: Environment Setup 
  hosts: localhost

  tasks:
    - name: Setting static facts
      set_fact:
        setup_pb_ran: true
        pb_run_types:
          - prod
          - local
          - test
    - name: Enter Run Type
      pause:
        prompt: "What run type do you wish to run in? (Choices: {{ pb_run_types }})"
      register: run_type_result
      until: run_type_result.user_input in pb_run_types
    - set_fact:
        pb_run_type: "{{ run_type_result.user_input }}"