volume_commands:
  - create
  - attach
  - both
volume_states:
  - present
  - absent
volume_providers:
  digital_ocean:
    volume_info: "providers/digitalocean/volume_info.yaml"
    volume_update: "providers/digitalocean/volume_update.yaml"
        