---
base_file_options: &base_file_options_ref
  dir_path:
    type: str
    required: true
    description: Directory path to file
  filename:
    type: str
    required: true
    description: Name of file
  overwrite:
    type: bool
    default: false
    description: Determines whether to overwrite file if exist

base_cert_options: &base_cert_options_ref
  cert:
    type: dict
    required: true
    description: Settings to store the host cert
    options: *base_file_options_ref

base_key_options: &base_key_options_ref
  key:
    type: dict
    required: true
    description: Settings to store the host private key
    options:
      <<: *base_file_options_ref

base_private_key_options: &base_private_key_options_ref
  private_key_file:
    type: str
    required: true
    description: Absolute filepath to private key

base_csr_options: &base_csr_options_ref
  csr:
    type: dict
    required: true
    description: Settings to store the host csr
    options: *base_file_options_ref

base_subject_alt_names_options: &base_subject_alt_names_options_ref
  subject_alt_names:
    type: list
    required: true
    elements: str
    description: List of names to represent current host

base_ca_options: &base_ca_options_ref
  ca:
    type: dict
    required: true
    description: CA settings to generate cert from given csr
    options:
      cert_content:
        type: str
        required: true
        description: CA certificate content
      private_key_content:
        type: str
        required: true
        description: CA private key content

base_csr_content_options: &base_csr_content_options_ref
  csr_content:
    type: str
    required: true
    description: CSR ready to be signed

base_common_name_options: &base_common_name_options_ref
  common_name:
    type: str
    required: true
    description: Common name for csr

# ------------------------------------------------------------------------

generate_cert_options: &generate_cert_options_ref
  <<: [*base_cert_options_ref, *base_ca_options_ref, *base_csr_content_options_ref]
  valid_not_after:
    type: str
    default: +365d
    description: Length of time in which cert is valid for in future
  valid_not_before:
    type: str
    default: -1d
    description: Length of time in which cert is valid for in past

generate_ca_cert_options: &generate_ca_cert_options_ref
  <<: [*base_private_key_options_ref, *base_cert_options_ref, *base_common_name_options_ref]

generate_csr_options: &generate_csr_options_ref
  <<: [
    *base_private_key_options_ref, 
    *base_csr_options_ref, 
    *base_subject_alt_names_options_ref,
    *base_common_name_options_ref
  ]

generate_private_key_options: &generate_private_key_options_ref
  <<: *base_key_options_ref

update_trusted_certs_options: &update_trusted_certs_options_ref
  cert:
    type: dict
    required: true
    description: Settings to store signed cert in trusted directory
    options:
      filename:
        type: str
        required: true
        description: Name of file
      overwrite:
        type: bool
        default: false
        description: Determines whether to overwrite file if exist
  ca_cert_content:
    type: str
    required: true
    description: Content of trusted CA cert

client_options: &client_options_ref
  <<: [
    *base_cert_options_ref, 
    *base_key_options_ref, 
    *base_csr_options_ref, 
    *base_subject_alt_names_options_ref,
    *base_ca_options_ref,
    *base_common_name_options_ref
  ]

argument_specs:
  generate_private_key:
    short_description: Generates private key
    description: Generates private key to be used creating cert
    options: *generate_private_key_options_ref

  generate_private_key_preflight:
    short_description: Generates private key preflight
    options: *generate_private_key_options_ref

  generate_ca_cert:
    short_description: Generates CA cert
    description: Generates CA cert so other nodes/users can use CA to sign CSRs
    options: *generate_ca_cert_options_ref

  generate_ca_cert_preflight:
    short_description: Generates CA cert preflight
    options: *generate_ca_cert_options_ref

  generate_csr:
    short_description: Generates CSR
    description: Generates CSR for CA cert to be signed by
    options: *generate_csr_options_ref

  generate_csr_preflight:
    short_description: Generates CSR preflight
    options: *generate_csr_options_ref

  generate_cert:
    short_description: Generate cert from CSR
    description: Generate cert from CSR using CA content
    options: *generate_cert_options_ref

  generate_cert_preflight:
    short_description: Signs CSR preflight
    options: *generate_cert_options_ref

  client:
    description: Create cert for client based on CA cert
    options: *client_options_ref

  client_preflight:
    description: SSL client preflight
    options: *client_options_ref
