---
- name: Assert hostvar names are not passed
  assert:
    that:
      - vagrant_content_list_hostvar not in ['vagrant_config', 'content_list']
      - vagrant_content_hostvar not in ['vagrant_config', 'content_list']

- name: Set empty array if 'vagrant_content_list_hostvar' doesn't exist
  when: hostvars['localhost'][vagrant_content_list_hostvar] is not defined
  set_fact:
    "{{ vagrant_content_list_hostvar }}": []

- name: Verify vagrant_hostvar is list
  when: hostvars['localhost'][vagrant_content_list_hostvar] is defined
  assert:
    that: "hostvars['localhost'][vagrant_content_list_hostvar] | type_debug == 'list'"
    fail_msg: Hostvar "vagrant_content_list_hostvar" is not of type list

- name: Set fact for content list
  set_fact:
    content_list: "{{ hostvars['localhost'][vagrant_content_list_hostvar] }}"

- name: Set up vagrant file content
  set_fact:
    vagrant_config: |
      config.vm.define "{{ vagrant.name }}" do |machine|
        machine.vm.hostname = {{ hostname }}
        machine.vm.box = {{ vagrant.box }}
        {% if 'box_version' in vagrant %}
        machine.vm.box_version = {{ vagrant.box_version }}
        {% endif %}
        
        machine.vm.network "public_network" ip: "{{ ip }}"

        {% if 'disks' in vagrant %}
        {% for disk in vagrant.disks %}
        machine.vm.disk :disk, name: "{{ disk.name }}", size: "{{ disk.size }}GB"
        {% endfor %}
        {% endif %}

        {% if 'specs' in vagrant %}
        machine.vm.provider :{{ vm_provider }} do |v|
          {% if 'memory' in vagrant.specs %}
          v.memory = {{ vagrant.specs.memory }}
          {% endif %}
          {% if 'cpus' in vagrant.specs %}
          v.cpus = {{ vagrant.specs.cpus }}
          {% endif %}
          {% if vm_provider == 'libvirt' %}
          v.default_prefix = ""
          {% endif %}
        end
        {% endif %}
      end

- name: Update list
  set_fact:
    content_list: "{{ content_list + [vagrant_config] }}"

- name: Update hostvar
  set_fact:
    "{{ vagrant_content_list_hostvar }}": "{{ content_list }}"
    "{{ vagrant_content_hostvar }}": "{{ content_list | join('\n') }}"
