---
- name: Import install task
  import_task: install.yml
  vars:
    vm_provider: "{{ vm_provider }}"
    project_root: "{{ project_root }}"

- name: Import run task
  import_task: run.yml
  vars:
    vm_provider: "{{ vm_provider }}"
    project_root: "{{ project_root }}"
    vagrants: "{{ vagrants }}"
