---
- name: Create vagrant project directory if not exists
  file:
    path: "{{ project_root }}"
    state: directory
    mode: 0777

- name: Set vagrant facts
  set_fact:
    vagrant_file_path: "{{ project_root }}/Vagrantfile"

- name: Remove old vagrant file
  file:
    path: "{{ vagrant_file_path }}"
    state: absent

- name: Use template to generate vagrant file
  template:
    src: vagrant.j2
    dest: "{{ vagrant_file_path }}"
    mode: 0777
  vars:
    vagrants: "{{ vagrants }}"

- name: Vagrant up
  command:
    chdir: "{{ project_root }}"
    cmd: vagrant up --provider="{{ vm_provider }}"
