---
- name: Set host file facts
  set_fact:
    dns: "{{ ip }} {{ hostname }} {{ fqdn }}"
    hosts_file: /etc/hosts

- name: Check host file for duplicates
  lineinfile:
    path: "{{ hosts_file }}"
    regexp: "{{ dns }}"
    state: absent
  check_mode: yes
  changed_when: false
  register: dns_check

- name: Update hosts file
  when: not dns_check.found
  lineinfile:
    path: "{{ hosts_file }}"
    state: present
    line: "{{ dns }}"
