---
minio1_path: &minio1_path_ref /mnt/minio1
minio2_path: &minio2_path_ref /mnt/minio2
minio3_path: &minio3_path_ref /mnt/minio3
minio4_path: &minio4_path_ref /mnt/minio4

ca_server_ip: &ca_server_ip_ref 192.168.3.2
ca_server_hostname: &ca_server_hostname_ref ca-server

dns_server_ip: &dns_server_ip_ref 192.168.3.3
dns_server_hostname: &dns_server_hostname_ref dns-server

pac_server1_ip: &pac_server1_ip_ref 192.168.3.4
pac_server1_hostname: &pac_server1_hostname_ref pac-server1

pac_server2_ip: &pac_server2_ip_ref 192.168.3.5
pac_server2_hostname: &pac_server2_hostname_ref pac-server2

pac_server3_ip: &pac_server3_ip_ref 192.168.3.6
pac_server3_hostname: &pac_server3_hostname_ref pac-server3

pac_server4_ip: &pac_server4_ip_ref 192.168.3.7
pac_server4_hostname: &pac_server4_hostname_ref pac-server4

pac_domain: &pac_domain_ref pac-dev.com

ca_server: &ca_server_ref
  ip: *ca_server_ip_ref

minio_docker: &minio_docker_ref
  name: minio
  from_collection: true
  image: minio/minio:RELEASE.2022-06-11T19-55-32Z
  vars:
    storage_paths:
      - *minio1_path_ref
      - *minio2_path_ref
      - *minio3_path_ref
      - *minio4_path_ref

node_exporter_docker: &node_exporter_docker_ref
  name: node_exporter
  from_collection: true
  image: prom/node-exporter:v1.3.1
  vars:
    storage_path: /mnt/storage/node_exporter

grafana_docker: &grafana_docker_ref
  name: grafana
  from_collection: true
  image: grafana/grafana:9.0.4
  vars:
    storage_path: /mnt/storage/grafana

prometheus_docker: &prometheus_docker_ref
  name: prometheus
  from_collection: true
  image: prom/prometheus:v2.37.0
  vars:
    storage_path: /mnt/storage/promethues

cockroachdb_docker: &cockroachdb_docker_ref
  name: cockroachdb
  from_collection: true
  image: cockroachdb/cockroach:v22.1.3
  vars:
    storage_path: /mnt/storage/cockroachdb

alert_manager_docker: &alert_manager_docker_ref
  name: alert_manager
  from_collection: true
  image: prom/alertmanager:v0.24.0
  vars:
    storage_path: /mnt/storage/alert_manager

redis_docker: &redis_docker_ref
  name: redis
  from_collection: true
  image: redis:6.2.4

user_creds: &user_creds_ref
  username: pac
  password: pac
  groups:
    - sudo

specs: &specs_ref
  memory: 2048
  cpus: 1

disks: &disks_ref
  - name: minio1
    path: *minio1_path_ref
    size: 1
  - name: minio2
    path: *minio2_path_ref
    size: 1
  - name: minio3
    path: *minio3_path_ref
    size: 1
  - name: minio4
    path: *minio4_path_ref
    size: 1

minio_server_specs: &minio_server_specs_ref
  memory: 2048
  cpus: 1
  disks: *disks_ref

dns_client: &dns_client_ref
  client:
    dns_server:
      ip: *dns_server_ip_ref

user_data: &user_data_ref
  users:
    - name: pac-user
      groups:
        - sudo

nameserver: &nameserver_ref
  type: nameserver
  address:
    - 192.168.3.3
    - 8.8.8.8

gateway: &gateway_ref 192.168.3.1
network_type: &network_type_ref physical
network_name: &network_name_ref eth0
network_version: &network_version_ref 1
subnet_type: &subnet_type_ref static
subnet_netmask: &subnet_netmask_ref 255.255.255.0

config:
  vm_provider: libvirt
  project_root: ~/.vagrant_projects/pac/libvirt
  terraform: {}
    
  droplets:
    - hostname: *ca_server_hostname_ref
      cloud_init:
        user_data: *user_data_ref
        network_config:
          network:
            version: *network_version_ref
            config:
              - type: *network_type_ref
                name: *network_name_ref
                subnets:
                  - type: *subnet_type_ref
                    address: *ca_server_ip_ref
                    netmask: *subnet_netmask_ref
                    gateway: *gateway_ref
              - *nameserver_ref
            # - type: nameserver
            #   address:
            #     - 192.168.3.3
            #     - 8.8.8.8
      specs: *specs_ref
      ca:
        server: {}
      docker_containers:
        - name: busybox
          image: busybox:1.35.0
    # - hostname: *dns_server_hostname_ref
    #   cloud_init:
    #     user_data: *user_data_ref
    #     network_config:
    #       version: *network_version_ref
    #       config:
    #         - type: *network_type_ref
    #           name: *network_name_ref
    #           subnets:
    #             - type: *subnet_type_ref
    #               address: *dns_server_ip_ref
    #               netmask: *subnet_netmask_ref
    #               gateway: *gateway_ref
    #         - *nameserver_ref
    #   specs: *specs_ref
    #   dns:
    #     server:
    #       corefile:
    #         records:
    #           - name: "."
    #             blocks:
    #               - name: whoami
    #               - name: forward
    #                 parameters:
    #                   - "."
    #                   - "8.8.8.8"
    #               - name: log
    #               - name: errors
    #               - name: cache
    #           - name: *pac_domain_ref
    #             blocks:
    #               - name: hosts
    #                 parameters:
    #                   - /etc/coredns/hosts/pac-dev.com
    #                   - *pac_domain_ref
    #                 blocks:
    #                   - name: ttl
    #                     parameters:
    #                       - 60
    #                   - name: reload
    #                     parameters:
    #                       - 5
    #       hosts:
    #         - host_file: *pac_domain_ref
    #           records:
    #             - ip: *pac_server1_ip_ref
    #               hostname: *pac_server1_hostname_ref
    #             - ip: *pac_server1_ip_ref
    #               hostname: minio1
    #             - ip: *pac_server2_ip_ref
    #               hostname: *pac_server2_hostname_ref
    #             - ip: *pac_server2_ip_ref
    #               hostname: minio2
    #             - ip: *pac_server3_ip_ref
    #               hostname: *pac_server3_hostname_ref
    #             - ip: *pac_server3_ip_ref
    #               hostname: minio3
    #             - ip: *pac_server4_ip_ref
    #               hostname: *pac_server4_hostname_ref
    #             - ip: *pac_server4_ip_ref
    #               hostname: minio4
    #   docker_containers:
    #     - name: busybox
    #       image: busybox:1.35.0
    # - hostname: *pac_server1_hostname_ref
    #   cloud_init:
    #     user_data: *user_data_ref
    #     network_config:
    #       version: *network_version_ref
    #       config:
    #         - type: *network_type_ref
    #           name: *network_name_ref
    #           subnets:
    #             - type: *subnet_type_ref
    #               address: *pac_server1_ip_ref
    #               netmask: *subnet_netmask_ref
    #               gateway: *gateway_ref
    #         - *nameserver_ref
    #   specs: *minio_server_specs_ref
    #   ca:
    #     client:
    #       ca_server: *ca_server_ref
    #       subject_alt_names:
    #         - "DNS:minio1.pac-dev.com"
    #         - "DNS:pac-server1.pac-dev.com"
    #   dns: *dns_client_ref
    #   docker_composes:
    #     - name: jasperreports
    #       from_collection: true
    #       params:
    #         # password
    #         # allow_empty_password
    #         services:
    #           mariadb:
    #             image: bitnami/mariadb:10.1.47
    #             storage_path: /mnt/storage/mariadb
    #           jasperreports:
    #             image: bitnami/jasperreports:6.4.3
    #             storage_path: /mnt/storage/jasperreports
    #   docker_containers:
    #     - *alert_manager_docker_ref
    #     - *node_exporter_docker_ref
    #     - *grafana_docker_ref
    #     - *prometheus_docker_ref
    #     - *minio_docker_ref
    # - hostname: *pac_server2_hostname_ref
    #   cloud_init:
    #     user_data: *user_data_ref
    #     network_config:
    #       version: *network_version_ref
    #       config:
    #         - type: *network_type_ref
    #           name: *network_name_ref
    #           subnets:
    #             - type: *subnet_type_ref
    #               address: *pac_server2_ip_ref
    #               netmask: *subnet_netmask_ref
    #               gateway: *gateway_ref
    #         - *nameserver_ref
    #   specs: *minio_server_specs_ref
    #   ca:
    #     client:
    #       ca_server: *ca_server_ref
    #       subject_alt_names:
    #         - "DNS:minio2.pac-dev.com"
    #         - "DNS:pac-server2.pac-dev.com"
    #   dns: *dns_client_ref
    #   docker_containers:
    #     - *node_exporter_docker_ref
    #     - *cockroachdb_docker_ref
    #     - *minio_docker_ref
    # - hostname: *pac_server3_hostname_ref
    #   cloud_init:
    #     user_data: *user_data_ref
    #     network_config:
    #       version: *network_version_ref
    #       config:
    #         - type: *network_type_ref
    #           name: *network_name_ref
    #           subnets:
    #             - type: *subnet_type_ref
    #               address: *pac_server3_ip_ref
    #               netmask: *subnet_netmask_ref
    #               gateway: *gateway_ref
    #         - *nameserver_ref
    #   specs: *minio_server_specs_ref
    #   ca:
    #     client:
    #       ca_server: *ca_server_ref
    #       subject_alt_names:
    #         - "DNS:minio3.pac-dev.com"
    #         - "DNS:pac-server3.pac-dev.com"
    #   dns: *dns_client_ref
    #   docker_containers:
    #     - *node_exporter_docker_ref
    #     - *cockroachdb_docker_ref
    #     - *minio_docker_ref
    # - hostname: *pac_server4_hostname_ref
    #   cloud_init:
    #     user_data: *user_data_ref
    #     network_config:
    #       version: *network_version_ref
    #       config:
    #         - type: *network_type_ref
    #           name: *network_name_ref
    #           subnets:
    #             - type: *subnet_type_ref
    #               address: *pac_server4_ip_ref
    #               netmask: *subnet_netmask_ref
    #               gateway: *gateway_ref
    #         - *nameserver_ref
    #   specs: *minio_server_specs_ref
    #   ca:
    #     client:
    #       ca_server: *ca_server_ref
    #       subject_alt_names:
    #         - "DNS:minio4.pac-dev.com"
    #         - "DNS:pac-server4.pac-dev.com"
    #   dns: *dns_client_ref
    #   docker_containers:
    #     - *node_exporter_docker_ref
    #     - *cockroachdb_docker_ref
    #     - *minio_docker_ref
