---
minio_vars:
  minio1: /mnt/minio1
  minio2: /mnt/minio2
  minio3: /mnt/minio3
  minio4: /mnt/minio4

droplets:
  - ip: 192.168.2.3
    user_creds:
      username: pac_user
      password: password
    mounts:
      - device: /dev/sdb
        mount_point: "{{ minio_vars.minio1 }}"
        fstype: xfs
      - device: /dev/sdc
        mount_point: "{{ minio_vars.minio2 }}"
        fstype: xfs
      - device: /dev/sdd
        mount_point: "{{ minio_vars.minio3 }}"
        fstype: xfs
      - device: /dev/sde
        mount_point: "{{ minio_vars.minio4 }}"
        fstype: xfs
    docker_types:
      - name: grafana
      - name: prometheus
      - name: minio
        vars:
          storage_paths:
            - "{{ minio_vars.minio1 }}"
            - "{{ minio_vars.minio2 }}"
            - "{{ minio_vars.minio3 }}"
            - "{{ minio_vars.minio4 }}"
