---
- name: Test random stuff
  hosts: localhost
  gather_facts: true

  tasks:
    # - name: Gather the package facts
    #   package_facts:
    #     manager: auto

    - name: List snap installed
      shell: snap list | grep blah
      ignore_errors: true
      register: snap_output

    - name: Show output
      debug:
        msg: "{{ snap_output }}"