---
- name: Test random stuff
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Set base facts
      set_fact:
        keys_path: /etc/ssl/private
        csrs_path: /home/server1-user/
        certs_path: /etc/ssl/certs/

    - name: Delegate to server1
      delegate_to: 10.151.165.2
      become: true
      remote_user: server1-user
      block:
        - name: Create CA private key
          import_role:
            name: traviss25.util.ssl
            tasks_from: generate_private_key
          vars:
            key:
              overwrite: true
              dir_path: "{{ keys_path }}"
              filename: master-ca.key

        - name: Create CA cert
          import_role:
            name: traviss25.util.ssl
            tasks_from: generate_ca_cert
          vars:
            common_ca_name: Master CA
            private_key_file: "{{ keys_path }}/master-ca.key"
            cert:
              overwrite: true
              dir_path: "{{ certs_path }}"
              filename: master-ca.crt

        - name: Create client private key
          import_role:
            name: traviss25.util.ssl
            tasks_from: generate_private_key
          vars:
            key:
              overwrite: true
              dir_path: "{{ keys_path }}"
              filename: client.key

        - name: Generate CSR
          import_role:
            name: traviss25.util.ssl
            tasks_from: generate_csr
          vars:
            private_key_file: "{{ keys_path }}/client.key"
            subject_alt_names:
              - "DNS:foo.test.com"
            csr:
              overwrite: true
              dir_path: "{{ csrs_path }}"
              filename: client.csr

        - name: Get CA private key content
          shell: "cat {{ keys_path }}/master-ca.key"
          register: ca_private_key_shell

        - name: Get CA cert content
          shell: "cat {{ certs_path }}/master-ca.crt"
          register: ca_cert_shell

        - name: Get CSR content
          shell: "cat {{ csrs_path }}/client.csr"
          register: client_csr_shell

        - name: Generate cert
          import_role:
            name: traviss25.util.ssl
            tasks_from: generate_cert
          vars:
            private_key_file: "{{ keys_path }}/client.key"
            csr_content: "{{ client_csr_shell.stdout }}"
            ca:
              cert_content: "{{ ca_cert_shell.stdout }}"
              private_key_content: "{{ ca_private_key_shell.stdout }}"
            cert:
              overwrite: true
              dir_path: "{{ certs_path }}"
              filename: client.crt

        - name: Update trusted certs
          import_role:
            name: traviss25.util.ssl
            tasks_from: update_trusted_certs
          vars:
            ca_cert_content: "{{ ca_cert_shell.stdout }}"
            cert:
              overwrite: true
              filename: master-ca.crt
            