---
- name: Generate CA certs
  hosts: localhost

  tasks:
    - name: Set base facts
      set_fact:
        minio_ca_dir: /home/travis/.minio/certs/CA
        cockroach_ca_dir: /home/travis/.cockroach-certs/CA

    - name: Set cert facts
      set_fact:
        minio_ca_key:
          overwrite: true
          dir_path: "{{ minio_ca_dir }}"
          filename: ca.key
        minio_ca_cert:
          overwrite: true
          dir_path: "{{ minio_ca_dir }}"
          filename: ca.crt
        cockroach_ca_key:
          overwrite: true
          dir_path: "{{ cockroach_ca_dir }}"
          filename: ca.key
        cockroach_ca_cert:
          overwrite: true
          dir_path: "{{ cockroach_ca_dir }}"
          filename: ca.crt

    - name: Create minio private key
      import_role:
        name: traviss25.util.tls
        tasks_from: generate_private_key
      vars:
        key: "{{ minio_ca_key }}"

    - name: Create cockroach private key
      import_role:
        name: traviss25.util.tls
        tasks_from: generate_private_key
      vars:
        key: "{{ cockroach_ca_key }}"

    - name: Create minio cert
      import_role:
        name: traviss25.util.tls
        tasks_from: generate_ca_cert
      vars:
        cert: "{{ minio_ca_cert }}"
        private_key_file: "{{ (minio_ca_key.dir_path, minio_ca_key.filename) | path_join }}"
        common_name: "Minio CA"

    - name: Create cockroach cert
      import_role:
        name: traviss25.util.tls
        tasks_from: generate_ca_cert
      vars:
        cert: "{{ cockroach_ca_cert }}"
        private_key_file: "{{ (cockroach_ca_key.dir_path, cockroach_ca_key.filename) | path_join }}"
        common_name: "Cockroach CA"

      
