---
- name: Assert droplets list passed
  assert:
    that:
      - droplets is defined
      - droplets | type_debug == "list"
      - droplets | length > 0
    fail_msg: Variable "droplets" is not defined / not a list

- name: Assert droplet list has correct properties
  loop: "{{ droplets }}"
  assert:
    that:
      - item.host is defined
      - item.docker_types is defined
      - item.docker_types | type_debug == 'list'
      - item.docker_types | length > 0
    fail_msg: |
      Requirements for each droplet object is:

      host: FQDN/IP of host to connect to
      docker_types: List of docker types to install on servers

- name: Assert correct docker types
  loop: "{{ droplets | subelements('docker_types') }}"
  assert:
    that: item.1.name in defaults.docker_type
    fail_msg: "{{ item.1.name }} is invalid docker type"

- name: Assert custom user creds are correct if set
  loop: "{{ droplets }}"
  when: item.user_creds is defined
  assert:
    that:
      - item.user_creds.username is defined
      - item.user_creds.groups is defined
      - item.user_creds.groups | type_debug == 'list'
      - item.user_creds.groups | length > 0
    fail_msg: Must set username and have at least one group attached to user

- name: Assert mounts are correct if set
  loop: "{{ droplets | subelements('mounts', skip_missing=True) }}"
  assert:
    that:
      - item.1.device is defined
      - item.1.mount_point is defined
      - item.1.fs is defined
      - item.1.fs in all_fstype_choices
    fail_msg: Must set "device", "mount_point" and "fs" variables for each "mounts" object
