---
- name: Set combine facts
  set_fact:
    csr_full_path: "{{ (csr.dir_path, csr.filename) | path_join }}"
    overwrite: "{{ csr.overwrite | default(false) }}"

- name: Get csr file stats
  stat:
    path: "{{ csr_full_path }}"
  register: csr_results

- name: Create csr directory
  file:
    state: directory
    path: "{{ csr.dir_path }}"

# - name: Create csr file
#   file:
#     state: touch
#     path: "{{ csr_full_path }}"

- name: CSR block
  when: not csr_results.stat.exists or overwrite
  block:
    - name: Create certificate signing request (CSR) for new certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ private_key_file }}"
        subject_alt_name: "{{ subject_alt_names }}"
      register: csr

    - name: Store csr content
      copy:
        remote_src: true
        content: "{{ csr.csr }}" 
        dest: "{{ csr_full_path }}"