---
vm_provider: &vm_provider_ref
  type: str
  default: virtualbox
  description: Determines what vm provider to install
  choices:
    - virtualbox
    - libvirt

project_root: &project_root_ref
  type: str
  required: true
  description: Root project folder to store vagrant info

vagrants: &vagrants_ref
  type: list
  elements: dict
  required: true
  description: |
    List of object settings describing how vagrant will be set up for current droplet
  options:
    name:
      type: str
      required: true
      description: Name of vm which should be unique
    box:
      type: str
      required: true
      description: VM image to use
    box_version:
      type: str
      description: Version of vm image to use
    disks:
      type: list
      elements: dict
      description: List of disk objects that is used to configure disk settings
      options:
        name:
          type: str
          required: true
          description: Name of disk
        size:
          type: int
          required: true
          description: Size of disk in GB
    specs:
      type: dict
      description: Specs object to set up vm
      options:
        memory:
          type: int
          description: Memory of vm in MB
        cpus:
          type: int
          description: Number of cpus for vm

install_options: &install_options_ref
  vm_provider: *vm_provider_ref
  project_root: *project_root_ref

run_options: &run_options_ref
  vm_provider: *vm_provider_ref
  project_root: *project_root_ref
  vagrants: *vagrants_ref

main_options: &main_options_ref
  vm_provider: *vm_provider_ref
  project_root: *project_root_ref
  vagrants: *vagrants_ref

argument_specs:
  main:
    description: Sets up vagrant environment from installing to running
    options: *main_options_ref

  main_preflight:
    description: Main preflight
    options: *main_options_ref

  install:
    short_description: Install vagrant
    description: Install vagrant and related plugins for provider
    options: *install_options_ref

  install_preflight:
    short_description: Install preflight
    options: *install_options_ref

  run:
    short_description: Run vagrant
    description: Run vagrant with given config file content
    options: *run_options_ref

  run_preflight:
    short_description: Run preflight
    options: *run_options_ref
