---
host_file_options: &host_file_options_ref
  file_state:
    type: str
    choices:
      - create
      - append
      - update
      - delete
    default: create
    description: Determines the state of file
  root_dir:
    type: str
    default: /etc/coredns/hosts
    description: Root dir of host files
  host_file:
    type: str
    required: true
    description: |
      Name of host format file.  
      Convention should be to name after domain eg. example.com
  records:
    type: list
    elements: dict
    required: true
    options:
      ip:
        type: str
        required: true
        description: IP address of host
      hostname:
        type: str
        required: true
        description: Host name for ip
      change_to_ip:
        type: str
        description: |
          Required when file_state is "update", will search file for "ip" and
          replace with this value
      change_to_hostname:
        type: str
        description: |
          Required when file_state is "update", will search file for "host" and
          replace with this value

corefile_options: &corefile_options_ref
  root_dir:
    type: str
    default: /etc/coredns
    description: Root dir of coredns file
  file_state:
    type: str
    choices:
      - create
      - append
      - delete
    default: create
    description: Determines the state of file
  records:
    type: list
    elements: dict
    description: Settings for Corefile if file_state is not "delete"
    options:
      name:
        type: str
        description: This is the outer most block where we declare domain/ports to listen for
      blocks:
        type: list
        elements: dict
        description: Blocks to use for server block
        options:
          name:
            type: str
            description: Name of plugin/parameter to use
          parameters:
            type: list
            elements: str
            description: Parameters to use for plugin
          blocks:
            type: list
            elements: dict
            description: Recursive list of this dict

main_options: &main_options_ref
  corefile:
    type: dict
    required: true
    description: Object settings for corefile
    options: *corefile_options_ref
  hosts:
    type: list
    elements: dict
    description: List of host object settings to generate host files
    options: *host_file_options_ref

argument_specs:
  main:
    description: Main entry into installing and running coredns
    options: *main_options_ref

  main_preflight:
    short_description: Main prelight for dns
    options: *main_options_ref

  host_file:
    description: Creates host format file for Corefile to use
    options: *host_file_options_ref

  host_file_preflight:
    description: Host file preflight for dns
    options: *host_file_options_ref

  corefile:
    description: Creates corefile config file
    options: *corefile_options_ref

  corefile_preflight:
    description: Corefile preflight for dns
    options: *corefile_options_ref
