---
dns_records:
  - ip: 192.168.2.2
    hostname: minio1
    fqdn: minio1.dev.com
  - ip: 192.168.2.3
    hostname: minio2
    fqdn: minio2.dev.com
  - ip: 192.168.2.4
    hostname: minio3
    fqdn: minio3.dev.com
  - ip: 192.168.2.5
    hostname: minio4
    fqdn: minio4.dev.com
