---
minio1_path: &minio1_path_ref /mnt/minio1
minio2_path: &minio2_path_ref /mnt/minio2
minio3_path: &minio3_path_ref /mnt/minio3
minio4_path: &minio4_path_ref /mnt/minio4

vm_box_image: &vm_box_image_ref generic/ubuntu2004

ca_server_ip: &ca_server_ip_ref 192.168.2.2
ca_server_hostname: &ca_server_hostname_ref ca-server

dns_server_ip: &dns_server_ip_ref 192.168.2.3
dns_server_hostname: &dns_server_hostname_ref dns-server

pac_server1_ip: &pac_server1_ip_ref 192.168.2.4
pac_server1_hostname: &pac_server1_hostname_ref pac-server1

pac_server2_ip: &pac_server2_ip_ref 192.168.2.5
pac_server2_hostname: &pac_server2_hostname_ref pac-server2

pac_server3_ip: &pac_server3_ip_ref 192.168.2.6
pac_server3_hostname: &pac_server3_hostname_ref pac-server3

pac_server4_ip: &pac_server4_ip_ref 192.168.2.7
pac_server4_hostname: &pac_server4_hostname_ref pac-server4

pac_domain: &pac_domain_ref pac-dev.com

minio_docker: &minio_docker_ref
  name: minio
  from_collection: true
  image: minio/minio:RELEASE.2022-06-11T19-55-32Z
  vars:
    storage_paths:
      - *minio1_path_ref
      - *minio2_path_ref
      - *minio3_path_ref
      - *minio4_path_ref

node_exporter_docker: &node_exporter_docker_ref
  name: node_exporter
  from_collection: true
  image: prom/node-exporter:v1.3.1
  vars:
    storage_path: /mnt/storage/node_exporter

grafana_docker: &grafana_docker_ref
  name: grafana
  from_collection: true
  image: grafana/grafana:9.0.4
  vars:
    storage_path: /mnt/storage/grafana

prometheus_docker: &prometheus_docker_ref
  name: prometheus
  from_collection: true
  image: prom/prometheus:v2.37.0
  vars:
    storage_path: /mnt/storage/promethues

cockroachdb_docker: &cockroachdb_docker_ref
  name: cockroachdb
  from_collection: true
  image: cockroachdb/cockroach:v22.1.3
  vars:
    storage_path: /mnt/storage/cockroachdb

alert_manager_docker: &alert_manager_docker_ref
  name: alert_manager
  from_collection: true
  image: prom/alertmanager:v0.24.0
  vars:
    storage_path: /mnt/storage/alert_manager

redis_docker: &redis_docker_ref
  name: redis
  from_collection: true
  image: redis:6.2.4

user_creds: &user_creds_ref
  username: vagrant
  password: vagrant
  groups:
    - sudo

specs: &specs_ref
  memory: 2048
  cpus: 1

mount1: &mount1_ref
  device: /dev/sdb
  mount_point: *minio1_path_ref
  fstype: xfs
mount2: &mount2_ref
  device: /dev/sdc
  mount_point: *minio2_path_ref
  fstype: xfs
mount3: &mount3_ref
  device: /dev/sdd
  mount_point: *minio3_path_ref
  fstype: xfs
mount4: &mount4_ref
  device: /dev/sde
  mount_point: *minio4_path_ref
  fstype: xfs

disks: &disks_ref
  - name: sdb
    size: 20
  - name: sdc
    size: 20
  - name: sdd
    size: 20
  - name: sde
    size: 20

mounts: &mounts_ref
  - *mount1_ref
  - *mount2_ref
  - *mount3_ref
  - *mount4_ref

dns_client: &dns_client_ref
  client:
    dns_server:
      ip: *dns_server_ip_ref

config:
  vm_provider: libvirt
  project_root: ~/.vagrant_projects/pac/libvirt

  droplets:
    - ip: *ca_server_ip_ref
      hostname: *ca_server_hostname_ref
      user_creds: *user_creds_ref
      ca:
        server: {}
      vagrant:
        name: *ca_server_hostname_ref
        box: *vm_box_image_ref
        specs: *specs_ref
      docker_containers:
        - name: busybox
          image: busybox:1.35.0
    - ip: *dns_server_ip_ref
      hostname: *dns_server_hostname_ref
      user_creds: *user_creds_ref
      dns:
        server:
          corefile:
            records:
              - name: "."
                blocks:
                  - name: whoami
                  - name: forward
                    parameters:
                      - "."
                      - "8.8.8.8"
                  - name: log
                  - name: errors
                  - name: cache
              - name: *pac_domain_ref
                blocks:
                  - name: hosts
                    parameters:
                      - /etc/coredns/hosts/pac-dev.com
                      - *pac_domain_ref
                    blocks:
                      - name: ttl
                        parameters:
                          - 60
                      - name: reload
                        parameters:
                          - 5
          hosts:
            - host_file: *pac_domain_ref
              records:
                - ip: *pac_server1_ip_ref
                  hostname: *pac_server1_hostname_ref
                - ip: *pac_server2_ip_ref
                  hostname: *pac_server2_hostname_ref
                - ip: *pac_server3_ip_ref
                  hostname: *pac_server3_hostname_ref
                - ip: *pac_server4_ip_ref
                  hostname: *pac_server4_hostname_ref
      vagrant:
        name: *dns_server_hostname_ref
        box: *vm_box_image_ref
        specs: *specs_ref
      docker_containers:
        - name: busybox
          image: busybox:1.35.0
    - ip: *pac_server1_ip_ref
      hostname: *pac_server1_hostname_ref
      user_creds: *user_creds_ref
      mounts: *mounts_ref
      ca:
        client:
          ca_server:
            ip: *ca_server_ip_ref
          subject_alt_names:
            - "DNS:minio1.pac-dev.com"
            - "DNS:pac-server1.pac-dev.com"
      dns: *dns_client_ref
      vagrant:
        name: *pac_server1_hostname_ref
        box: *vm_box_image_ref
        specs: *specs_ref
        disks: *disks_ref
      docker_composes:
        - name: jasperreports
          from_collection: true
          params:
            # password
            # allow_empty_password
            services:
              mariadb:
                image: bitnami/mariadb:10.1.47
                storage_path: /mnt/storage/mariadb
              jasperreports:
                image: bitnami/jasperreports:6.4.3
                storage_path: /mnt/storage/jasperreports
      docker_containers:
        - *alert_manager_docker_ref
        - *node_exporter_docker_ref
        - *grafana_docker_ref
        - *prometheus_docker_ref
        - *minio_docker_ref
    - ip: *pac_server2_ip_ref
      hostname: *pac_server2_hostname_ref
      user_creds: *user_creds_ref
      mounts: *mounts_ref
      ca:
        client:
          ca_server:
            ip: *ca_server_ip_ref
          subject_alt_names:
            - "DNS:minio2.pac-dev.com"
            - "DNS:pac-server2.pac-dev.com"
      dns: *dns_client_ref
      vagrant:
        name: *pac_server2_hostname_ref
        box: *vm_box_image_ref
        specs: *specs_ref
        disks: *disks_ref
      docker_containers:
        - *node_exporter_docker_ref
        - *cockroachdb_docker_ref
        - *minio_docker_ref
    - ip: *pac_server3_ip_ref
      hostname: *pac_server3_hostname_ref
      user_creds: *user_creds_ref
      mounts: *mounts_ref
      ca:
        client:
          ca_server:
            ip: *ca_server_ip_ref
          subject_alt_names:
            - "DNS:minio3.pac-dev.com"
            - "DNS:pac-server3.pac-dev.com"
      dns: *dns_client_ref
      vagrant:
        name: *pac_server3_hostname_ref
        box: *vm_box_image_ref
        specs: *specs_ref
        disks: *disks_ref
      docker_containers:
        - *node_exporter_docker_ref
        - *cockroachdb_docker_ref
        - *minio_docker_ref
    - ip: *pac_server4_ip_ref
      hostname: *pac_server4_hostname_ref
      user_creds: *user_creds_ref
      mounts: *mounts_ref
      ca:
        client:
          ca_server:
            ip: *ca_server_ip_ref
          subject_alt_names:
            - "DNS:minio4.pac-dev.com"
            - "DNS:pac-server4.pac-dev.com"
      dns: *dns_client_ref
      vagrant:
        name: *pac_server4_hostname_ref
        box: *vm_box_image_ref
        specs: *specs_ref
        disks: *disks_ref
      docker_containers:
        - *node_exporter_docker_ref
        - *cockroachdb_docker_ref
        - *minio_docker_ref
