---
- name: Update repositories
  apt:
    update_cache: yes

- name: Gather the package facts
  package_facts:
    manager: auto

- name: Install docker and deps
  become: true
  when: "'docker-ce' not in ansible_facts.packages"
  block:
    - name: Install package dependencies
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip

    - name: Install docker sdk for python
      shell: pip3 install docker

    - name: Create key ring dir
      file:
        state: directory
        path: /etc/apt/keyrings

    - name: Download and apply gpg
      shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Add repository to apt sources
      shell:
        cmd: |
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update repositories
      apt:
        update_cache: yes

    # Docker version: 5:20.10.17~3-0~ubuntu-focal

    - name: Install docker packages
      ignore_errors: true
      apt:
        pkg:
          - "docker-ce={{ docker_version | default(run_defaults.docker_version) }}"
          - "docker-ce-cli={{ docker_version | default(run_defaults.docker_version) }}"

    - name: Add user(s) to docker group
      loop: "{{ users | default([]) }}"
      loop_control:
        loop_var: user
      user:
        name: "{{ user }}"
        groups: docker
        append: yes

- name: Reset ssh connection
  meta:
    reset_connection
